version: "2"

services:
 backup:
  build:
    context: build
    args:
      ACCESS_TOKEN: "minetest-mirrors:<omitted>"
  restart: always
  volumes:
   - "git_cache:/git_cache"

volumes:
  git_cache: {}
