name: advtrains

on:
#  push:
#    branches: ['master']
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.2

    - name: mirror
      run: ./mirror.sh
      env:
        source_repo: https://git.bananach.space/advtrains.git
        github_repo: advtrains.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}
