name: easyvend

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3

    - name: mirror
      run: ./mirror.sh
      env:
        source_repo: https://repo.or.cz/minetest_easyvend.git
        github_repo: easyvend.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}
