name: notabug-org

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: cblocks
      run: ./mirror.sh
      env:
        source_repo:  https://notabug.org/TenPlus1/cblocks.git
        github_repo: cblocks.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: pbj_pup
      run: ./mirror.sh
      env:
        source_repo:  https://notabug.org/TenPlus1/pbj_pup.git
        github_repo: pbj_pup.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: pie
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/pie.git
        github_repo: pie.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: bonemeal
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/bonemeal.git
        github_repo: bonemeal.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: mobs_redo
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/mobs_redo.git
        github_repo: mobs_redo.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: mobs_animal
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/mobs_animal.git
        github_repo: mobs_animal.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: mobs_monster
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/mobs_monster.git
        github_repo: mobs_monster.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: mobs_water
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/mobs_water.git
        github_repo: mobs_water.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: mob_horse
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/mob_horse.git
        github_repo: mob_horse.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: ambience
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/ambience.git
        github_repo: ambience.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: bakedclay
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/bakedclay.git
        github_repo: bakedclay.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: farming
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/farming.git
        github_repo: farming.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: wine
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/wine.git
        github_repo: wine.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: falling_item
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/falling_item.git
        github_repo: falling_item.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: bees
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/bees.git
        github_repo: bees.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: ethereal
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/ethereal.git
        github_repo: ethereal.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: hopper
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/hopper.git
        github_repo: hopper.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: itemframes
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/itemframes.git
        github_repo: itemframes.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: mobs_npc
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/mobs_npc.git
        github_repo: mobs_npc.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: caverealms_lite
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/caverealms_lite.git
        github_repo: caverealms_lite.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}