name: notabug-org

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: bonemeal
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/bonemeal.git
        github_repo: bonemeal.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: mobs_redo
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/mobs_redo.git
        github_repo: mobs_redo.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: mobs_animal
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/mobs_animal.git
        github_repo: mobs_animal.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: ambience
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/ambience.git
        github_repo: ambience.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: bakedclay
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/bakedclay.git
        github_repo: bakedclay.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: farming
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/farming.git
        github_repo: farming.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: wine
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/wine.git
        github_repo: wine.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: falling_item
      run: ./mirror.sh
      env:
        source_repo: https://notabug.org/TenPlus1/falling_item.git
        github_repo: falling_item.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}
