name: repo-or-cz

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: minetest_easyvend
      run: ./mirror.sh
      env:
        source_repo: https://repo.or.cz/minetest_easyvend.git
        github_repo: easyvend.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: mirror
      run: ./mirror.sh
      env:
        source_repo: https://repo.or.cz/minetest_hbarmor.git
        github_repo: hbarmor.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: mirror
      run: ./mirror.sh
      env:
        source_repo: https://repo.or.cz/minetest_hudbars.git
        github_repo: hudbars.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}
